# Generated by Django 4.1.6 on 2023-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0008_auto_20200327_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
