# Generated by Django 4.1.6 on 2023-02-09 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0009_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
